apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-configuracao
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-configuracao
  template:
    metadata:
      labels:
        app: app-configuracao
    spec:
      containers:
        - name: app-configuracao
          image: vianconi/app-variaveis-ambiente:v2
          ports:
            - containerPort: 3000
          env:
          - name: APP_NAME
            value: "Minha Aplicacao Kubernetes"
          - name: APP_VERSION
            value: "2.5"
          - name: APP_AUTHOR
            value: "Etan&Zoe"
---
apiVersion: v1
kind: Service
metadata:
  name: app-configuracao
spec:
  selector:
    app: app-configuracao
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    name: http
    protocol: TCP
    nodePort: 30000